mysql:
  image: mysql:5.7
  imagePullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3306
  persistence:
    enabled: true
    storageClass: ebs
    size: 10Gi
  rootPassword: password
  database: test_db
  user: root
  password: password

flask:
  image: flask-app:latest
  imagePullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  env:
    MYSQL_SERVER: mysql
    MYSQL_USER: root
    MYSQL_PASSWORD: password
    MYSQL_DB: test_db
