apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  MYSQL_SERVER: {{ .Values.mysql.service.name }}
  MYSQL_USER: {{ .Values.mysql.user }}
  MYSQL_DB: {{ .Values.mysql.database }}
